CREATE TABLE QUARTO(
    NUMERO INTEGER PRIMARY KEY,
    ANDAR INTEGER NOT NULL
);

CREATE TABLE ESPECIALIDADE(
    CODIGO INTEGER PRIMARY KEY,
    NOME VARCHAR2(255)
);

CREATE TABLE MEDICO(
    CRM INTEGER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    SALARIO NUMBER NOT NULL,
    FK_ESPECIALIDADE INTEGER,
    FOREIGN KEY (FK_ESPECIALIDADE) REFERENCES ESPECIALIDADE(CODIGO)
);

CREATE TABLE PACIENTE(
    ID_PACIENTE INTEGER PRIMARY KEY,
    CPF VARCHAR2(255) UNIQUE NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    RG VARCHAR2(255) UNIQUE NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    FK_QUARTO INTEGER,
    FK_MEDICO INTEGER,
    FOREIGN KEY (FK_QUARTO) REFERENCES QUARTO(NUMERO),
    FOREIGN KEY (FK_MEDICO) REFERENCES MEDICO(CRM)
);

CREATE TABLE TELEFONE(
    ID_TELEFONE INTEGER PRIMARY KEY,
    FK_ID_PACIENTE INTEGER,
    FOREIGN KEY (FK_ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE TEM(
    FK_CRM INTEGER NOT NULL,
    FK_ID_PACIENTE INTEGER NOT NULL,
    HORARIO TIMESTAMP,
    FOREIGN KEY (FK_CRM) REFERENCES MEDICO(CRM),
    FOREIGN KEY (FK_ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    PRIMARY KEY (FK_CRM, FK_ID_PACIENTE, HORARIO)
);

DROP TABLE QUARTO;
DROP TABLE ESPECIALIDADE;
DROP TABLE MEDICO;
DROP TABLE PACIENTE;
DROP TABLE TELEFONE;
DROP TABLE TEM;
